Use prepend instead of include for AS::NumericWithFormat

diff --git a/gems/activesupport/6.0/_scripts/test b/gems/activesupport/6.0/_scripts/test
--- a/gems/activesupport/6.0/_scripts/test
+++ b/gems/activesupport/6.0/_scripts/test
@@ -1,8 +1,21 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -xe
+# set -eou => Exit command with non-zero status code, Output logs of every command executed, Treat unset variables as an error when substituting.
+set -eou pipefail
+# Internal Field Separator - Linux shell variable
+IFS=$'\n\t'
+# Print shell input lines
+set -v
 
-REPO=$(git rev-parse --show-toplevel)/gems
-rbs --repo=$REPO \
+# Set RBS_DIR variable to change directory to execute type checks using `steep check`
+RBS_DIR=$(cd $(dirname $0)/..; pwd)
+# Set REPO_DIR variable to validate RBS files added to the corresponding folder
+REPO_DIR=$(cd $(dirname $0)/../../..; pwd)
+# Validate RBS files, using the bundler environment present
+bundle exec rbs --repo=$REPO_DIR \
   -rmonitor -rdate -rsingleton -rlogger -rmutex_m -rtime \
   -ractivesupport validate --silent
+
+cd ${RBS_DIR}/_test
+# Run type checks
+bundle exec steep check
